
package view;


import java.util.logging.Level;
import java.util.logging.Logger;
import model.DAO.CadastroDAO;
import javax.swing.JOptionPane;
import model.Cadastro;


public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        jLabelcpf = new javax.swing.JLabel();
        jLabelendereco = new javax.swing.JLabel();
        jLabel9complemento = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jTextFieldtelefone = new javax.swing.JTextField();
        jTextFieldcpf = new javax.swing.JTextField();
        jTextFieldendereco = new javax.swing.JTextField();
        jTextFieldcomplemento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabelsobrenome = new javax.swing.JLabel();
        jTextFieldsobrenome = new javax.swing.JTextField();
        jLabelimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultório Odontológico");
        setMinimumSize(new java.awt.Dimension(556, 515));
        getContentPane().setLayout(null);

        nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Nome");
        getContentPane().add(nome);
        nome.setBounds(120, 160, 50, 20);

        Senha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setText("Senha");
        getContentPane().add(Senha);
        Senha.setBounds(120, 250, 80, 20);

        email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail");
        getContentPane().add(email);
        email.setBounds(120, 220, 34, 16);

        telefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("Telefone");
        getContentPane().add(telefone);
        telefone.setBounds(120, 280, 80, 20);

        jLabelcpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelcpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcpf.setText("Cpf");
        getContentPane().add(jLabelcpf);
        jLabelcpf.setBounds(120, 310, 60, 20);

        jLabelendereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelendereco.setForeground(new java.awt.Color(255, 255, 255));
        jLabelendereco.setText("Endereço");
        getContentPane().add(jLabelendereco);
        jLabelendereco.setBounds(120, 340, 80, 20);

        jLabel9complemento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9complemento.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9complemento.setText("Complemento");
        getContentPane().add(jLabel9complemento);
        jLabel9complemento.setBounds(120, 370, 79, 20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CADASTRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 30, 210, 40);
        getContentPane().add(jTextFieldnome);
        jTextFieldnome.setBounds(200, 160, 170, 22);

        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldemail);
        jTextFieldemail.setBounds(200, 220, 170, 22);
        getContentPane().add(jPasswordFieldsenha);
        jPasswordFieldsenha.setBounds(200, 250, 170, 22);

        jTextFieldtelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldtelefone);
        jTextFieldtelefone.setBounds(200, 280, 170, 22);

        jTextFieldcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcpfActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcpf);
        jTextFieldcpf.setBounds(200, 310, 170, 22);

        jTextFieldendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldenderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldendereco);
        jTextFieldendereco.setBounds(200, 340, 170, 22);

        jTextFieldcomplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcomplementoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldcomplemento);
        jTextFieldcomplemento.setBounds(200, 370, 170, 22);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 430, 110, 23);

        jLabelsobrenome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelsobrenome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsobrenome.setText("Sobrenome");
        getContentPane().add(jLabelsobrenome);
        jLabelsobrenome.setBounds(120, 190, 70, 16);
        getContentPane().add(jTextFieldsobrenome);
        jTextFieldsobrenome.setBounds(200, 190, 170, 22);

        jLabelimage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelimage.setForeground(new java.awt.Color(255, 255, 255));
        jLabelimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dentistanull.jpg"))); // NOI18N
        jLabelimage.setText("jLabel1");
        jLabelimage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelimage);
        jLabelimage.setBounds(0, 0, 562, 492);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jTextFieldtelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtelefoneActionPerformed

    private void jTextFieldcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcpfActionPerformed

    private void jTextFieldenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldenderecoActionPerformed

    private void jTextFieldcomplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcomplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcomplementoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            String nome =jTextFieldnome.getText();
            String sobrenome = jTextFieldsobrenome.getText();
            String senha = jPasswordFieldsenha.getText();
            String email = jTextFieldemail.getText();
            String telefone = jTextFieldtelefone.getText();
            String cpf = jTextFieldcpf.getText();
            String endereco = jTextFieldendereco.getText();
            String complemento= jTextFieldcomplemento.getText();
            
            Cadastro cadastro = new Cadastro(nome, sobrenome, senha, email, telefone, cpf, endereco, complemento );
            CadastroDAO cadastroDAO = new CadastroDAO();
            cadastroDAO.adicionar(cadastro);
            
            /*PROBLEMA*/
            JOptionPane.showMessageDialog(null, "Usuário cadastrado no sistema");
            usuario tc = new usuario();
            this.dispose();
            tc.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9complemento;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabelendereco;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JLabel jLabelsobrenome;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JTextField jTextFieldcomplemento;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldsobrenome;
    private javax.swing.JTextField jTextFieldtelefone;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
