package view;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Cadastro;
import model.Consulta;
import model.DAO.CadastroDAO;
import model.DAO.ConsultaDAO;

public class consulta extends javax.swing.JFrame {

    /**
     * Creates new form consulta
     */
    public consulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelsobrenome = new javax.swing.JLabel();
        jLabeldata = new javax.swing.JLabel();
        jLabelhora = new javax.swing.JLabel();
        jLabelnome = new javax.swing.JLabel();
        jComboBoxservicos = new javax.swing.JComboBox<>();
        jComboBoxplanos = new javax.swing.JComboBox<>();
        jToggleButtonagendar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaobs = new javax.swing.JTextArea();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldsobrenome = new javax.swing.JTextField();
        jTextFielddata = new javax.swing.JTextField();
        jTextFieldcpf = new javax.swing.JTextField();
        jLabelplanos = new javax.swing.JLabel();
        jLabelservicos = new javax.swing.JLabel();
        jLabelcpf = new javax.swing.JLabel();
        jLabelObsersacao = new javax.swing.JLabel();
        jComboBoxhora = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultório Odontológico");
        setMinimumSize(new java.awt.Dimension(860, 520));
        getContentPane().setLayout(null);

        jLabelsobrenome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelsobrenome.setText("Sobrenome");
        getContentPane().add(jLabelsobrenome);
        jLabelsobrenome.setBounds(190, 170, 70, 16);

        jLabeldata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabeldata.setText("Data");
        getContentPane().add(jLabeldata);
        jLabeldata.setBounds(190, 230, 40, 20);

        jLabelhora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelhora.setText("Hora");
        getContentPane().add(jLabelhora);
        jLabelhora.setBounds(190, 260, 70, 16);

        jLabelnome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelnome.setText("Nome");
        getContentPane().add(jLabelnome);
        jLabelnome.setBounds(190, 140, 80, 16);

        jComboBoxservicos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpeza", "Lentes", "Aparelhos", "Lentes", "Outros..." }));
        jComboBoxservicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxservicosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxservicos);
        jComboBoxservicos.setBounds(260, 320, 110, 22);

        jComboBoxplanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metlife", "Odontplus", "Sem planos" }));
        getContentPane().add(jComboBoxplanos);
        jComboBoxplanos.setBounds(260, 290, 110, 22);

        jToggleButtonagendar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jToggleButtonagendar.setText("AGENDAR");
        jToggleButtonagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonagendarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonagendar);
        jToggleButtonagendar.setBounds(424, 363, 380, 50);

        jTextAreaobs.setColumns(20);
        jTextAreaobs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaobs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 390, 230);
        getContentPane().add(jTextFieldnome);
        jTextFieldnome.setBounds(260, 140, 110, 22);
        getContentPane().add(jTextFieldsobrenome);
        jTextFieldsobrenome.setBounds(260, 170, 110, 22);

        jTextFielddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielddata);
        jTextFielddata.setBounds(260, 230, 110, 22);
        getContentPane().add(jTextFieldcpf);
        jTextFieldcpf.setBounds(260, 200, 110, 22);

        jLabelplanos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelplanos.setText("Planos");
        getContentPane().add(jLabelplanos);
        jLabelplanos.setBounds(190, 290, 35, 16);

        jLabelservicos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelservicos.setText("Serviços");
        getContentPane().add(jLabelservicos);
        jLabelservicos.setBounds(190, 320, 47, 16);

        jLabelcpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelcpf.setText("Cpf");
        getContentPane().add(jLabelcpf);
        jLabelcpf.setBounds(190, 200, 19, 16);

        jLabelObsersacao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelObsersacao.setText("Observação");
        getContentPane().add(jLabelObsersacao);
        jLabelObsersacao.setBounds(580, 110, 70, 16);

        jComboBoxhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9:00", "10:00", "11:00", "14:00", "15:00", "16:00", "17:00" }));
        getContentPane().add(jComboBoxhora);
        jComboBoxhora.setBounds(260, 260, 110, 22);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaprincipal.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 870, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private String[] getPlanos (){
    
      return  new String[] { "Metlife", "Odontplus", "Sem planos" };
        
    }
    
    private void jComboBoxservicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxservicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxservicosActionPerformed

    private void jTextFielddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddataActionPerformed

    private void jToggleButtonagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonagendarActionPerformed
        try {
            String nome =jTextFieldnome.getText();
            String sobrenome = jTextFieldsobrenome.getText();
            String cpf = jTextFieldcpf.getText();
            String obs = jTextAreaobs.getText();
            String dataString = jTextFielddata.getText();
            Date data = this.convertData(dataString);
            String hora = (String) jComboBoxhora.getSelectedItem();
            String servicos = (String) jComboBoxservicos.getSelectedItem();
            String planos = (String) jComboBoxplanos.getSelectedItem();
            

            
            Consulta consulta = new Consulta( nome, sobrenome, cpf, data, hora, planos, servicos, obs );
            ConsultaDAO consultaDAO = new ConsultaDAO();
            consultaDAO.adicionar(consulta);
            
            var mensagem = "Consulta agendada para o dia " + dataString + " ás " + hora + " horas ";
            JOptionPane.showMessageDialog(null, mensagem);

        } catch (Exception ex) {
            Logger.getLogger(cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButtonagendarActionPerformed

    private Date convertData(String data) {

        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date startDate;
        try {
            startDate = df.parse(data);
           
            System.out.println(startDate);
            return  startDate;
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Formato de data inválido, use o formato dd/mm/yyyy");
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxhora;
    private javax.swing.JComboBox<String> jComboBoxplanos;
    private javax.swing.JComboBox<String> jComboBoxservicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelObsersacao;
    private javax.swing.JLabel jLabelcpf;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JLabel jLabelhora;
    private javax.swing.JLabel jLabelnome;
    private javax.swing.JLabel jLabelplanos;
    private javax.swing.JLabel jLabelservicos;
    private javax.swing.JLabel jLabelsobrenome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaobs;
    private javax.swing.JTextField jTextFieldcpf;
    private javax.swing.JTextField jTextFielddata;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldsobrenome;
    private javax.swing.JToggleButton jToggleButtonagendar;
    // End of variables declaration//GEN-END:variables
}
